
# Serving
detach:  false
port:    8002
host:    0.0.0.0
baseurl: "" # does not include hostname

title: Ganessh Kumar
email:
description: Personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ganesshkumar.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ganesshkumar
github_username:  ganesshkumar
linkedin_user:    in/ganessh-kumar-r-p-676a4719

# Header
header_pages:
  - pages/projects.html
  - pages/archive.html
  - pages/about.md


# Pagination
paginate:      10
paginate_path: "/blog/page:num/"

# Custom Collection
collections:
  - projects

# Outputting
permalink:     /:year/:month/:day/:title.html
timezone:      Asia/Kolkata

# Analytics
google_analytics: "UA-65961333-1"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
