# Website info
name: 'Ganessh Kumar'
description: "Personal Blog"

author: 'Ganessh Kumar'
nickname: ganesshkumar
bio: 'Software Enginner'
location: ''
url: 'http://www.ganesshkumar.com'
image: 'assets/images/ganesshkumar.png'

markdown: kramdown
language: 'en-uk'

short_url: 'http://www.ganesshkumar.com'
baseurl: /

# Pagination
paginate: 10

# Custom Collection
collections:
  - projects

# Outputting
permalink:     /:year/:month/:day/:title.html
timezone:      Asia/Kolkata

# Analytics
google_analytics: "UA-65961333-1"
disqus: ganesshkumar

# gems and other configs
gems: [jekyll-paginate]
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
