name: Ganessh Kumar
description: Personal Blog
meta_description: "Personal blog"

markdown: kramdown
highlighter: rouge
logo: false
baseurl: ''
domain_name: 'http://www.ganesshkumar.com'
google_analytics: 'UA-65961333-1'
disqus_username: ganesshkumar
plugins: [jekyll-paginate]

# details for the RSS feed generator
url:            'http://www.ganesshkumar.com'
author:         'ganesshkumar'

# pagination
paginate:      10

# outputting
permalink:     /:year/:month/:day/:title.html
timezone:      Asia/Kolkata


# custom collection
collections:
  - projects

exclude:
  - Gemfile
  - Gemfile.lock

# local serving
detach:  false
port:    4002
host:    0.0.0.0
